version: '3.7'

services: 
  server:
    build:
      context: docker/server
    image: apache  
    ports:
      - 80:80
    volumes:
      - ./:/var/www/html
      - ./storage/app/public/:/var/www/public/storage/
    networks:
      - internal

  db:
    build: ./docker/pgsql
    image: pgsql
    ports:
      - 5432:5432
    volumes:
      - ./docker/pgsql/init:/docker-entrypoint-initdb.d
      - ./docker/pgsql/pgdata:/var/lib/postgresql
    environment:
      - POSTGRES_DB=${DB_DATABASE}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    networks:
      - internal

  #db:
    #build: ./docker/mysql
    #image: mysql
    #ports:
      #- 3306:3306
    #volumes:
      #- ./docker/mysql/init:/docker-entrypoint-initdb.d
      #- ./docker/mysql/mydata:/var/lib/mysql
    #environment:
      #- MYSQL_DB=${DB_DATABASE}
      #- MYSQL_USER=${DB_USERNAME}
      #- MYSQL_PASSWORD=${DB_PASSWORD}
      #- MYSQL_ALLOW_EMPTY_PASSWORD=true
    #networks:
      #- internal
      
networks:
  internal:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.220.0/28
